### ISSUE TITLE
Question to your writeup-documentation

### ISSUE THREAD

**Issue by rabbl** [kontez/writeups#1]
Hi,
thanks for posting the CTF-Writeups.
Great work.

I have a question to the terminal commands you're using:

For example: 

```
35C3CTF http GET 35.207.169.47  Accept-Language:....//....//....//....//....//....//....//....//flag
```
Is this a real command or only meta to make it understandable what you've done?
If real, whats the http-command?

Thanks

**Comment by kontez** [comment]
Hey!

I am using this tool: https://httpie.org/

Cheers

**Comment by rabbl** [comment]
Thanks!!! 
This is what I ever wanted ;)
Closing the issue!
